/**
 * US to Australian English spelling mappings
 * Based on Australian Government Style Manual guidance
 * https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/spelling
 */

const US_TO_AU_SPELLINGS = {
    // -ize → -ise (comprehensive list)
    "acclimatize": "acclimatise",
    "agonize": "agonise",
    "alphabetize": "alphabetise",
    "amortize": "amortise",
    "antagonize": "antagonise",
    "apologize": "apologise",
    "authorize": "authorise",
    "baptize": "baptise",
    "capitalize": "capitalise",
    "categorize": "categorise",
    "cauterize": "cauterise",
    "centralize": "centralise",
    "characterize": "characterise",
    "civilize": "civilise",
    "colonize": "colonise",
    "compartmentalize": "compartmentalise",
    "computerize": "computerise",
    "conceptualize": "conceptualise",
    "contextualize": "contextualise",
    "criticize": "criticise",
    "customize": "customise",
    "decentralize": "decentralise",
    "decolonize": "decolonise",
    "democratize": "democratise",
    "demobilize": "demobilise",
    "demonize": "demonise",
    "depoliticize": "depoliticise",
    "digitize": "digitise",
    "disincentivize": "disincentivise",
    "disorganize": "disorganise",
    "dramatize": "dramatise",
    "economize": "economise",
    "emphasize": "emphasise",
    "energize": "energise",
    "epitomize": "epitomise",
    "equalize": "equalise",
    "evangelize": "evangelise",
    "exorcize": "exorcise",
    "externalize": "externalise",
    "familiarize": "familiarise",
    "fantasize": "fantasise",
    "federalize": "federalise",
    "fertilize": "fertilise",
    "finalize": "finalise",
    "formalize": "formalise",
    "fossilize": "fossilise",
    "galvanize": "galvanise",
    "generalize": "generalise",
    "glamorize": "glamorise",
    "globalize": "globalise",
    "harmonize": "harmonise",
    "homogenize": "homogenise",
    "hospitalize": "hospitalise",
    "humanize": "humanise",
    "hybridize": "hybridise",
    "hypnotize": "hypnotise",
    "hypothesize": "hypothesise",
    "idealize": "idealise",
    "immobilize": "immobilise",
    "immunize": "immunise",
    "incentivize": "incentivise",
    "individualize": "individualise",
    "industrialize": "industrialise",
    "initialize": "initialise",
    "institutionalize": "institutionalise",
    "internalize": "internalise",
    "internationalize": "internationalise",
    "ionize": "ionise",
    "italicize": "italicise",
    "itemize": "itemise",
    "jeopardize": "jeopardise",
    "legalize": "legalise",
    "legitimize": "legitimise",
    "liberalize": "liberalise",
    "lionize": "lionise",
    "localize": "localise",
    "magnetize": "magnetise",
    "marginalize": "marginalise",
    "materialize": "materialise",
    "maximize": "maximise",
    "mechanize": "mechanise",
    "memorize": "memorise",
    "mesmerize": "mesmerise",
    "metabolize": "metabolise",
    "militarize": "militarise",
    "minimize": "minimise",
    "mobilize": "mobilise",
    "modernize": "modernise",
    "monetize": "monetise",
    "monopolize": "monopolise",
    "moralize": "moralise",
    "nationalize": "nationalise",
    "naturalize": "naturalise",
    "neutralize": "neutralise",
    "normalize": "normalise",
    "optimize": "optimise",
    "organize": "organise",
    "ostracize": "ostracise",
    "oxidize": "oxidise",
    "pasteurize": "pasteurise",
    "patronize": "patronise",
    "penalize": "penalise",
    "personalize": "personalise",
    "plagiarize": "plagiarise",
    "polarize": "polarise",
    "politicize": "politicise",
    "popularize": "popularise",
    "pressurize": "pressurise",
    "prioritize": "prioritise",
    "privatize": "privatise",
    "professionalize": "professionalise",
    "publicize": "publicise",
    "pulverize": "pulverise",
    "radicalize": "radicalise",
    "randomize": "randomise",
    "rationalize": "rationalise",
    "realize": "realise",
    "recognize": "recognise",
    "regularize": "regularise",
    "reorganize": "reorganise",
    "revitalize": "revitalise",
    "revolutionize": "revolutionise",
    "romanticize": "romanticise",
    "sanitize": "sanitise",
    "satirize": "satirise",
    "scandalize": "scandalise",
    "scrutinize": "scrutinise",
    "secularize": "secularise",
    "sensitize": "sensitise",
    "serialize": "serialise",
    "sexualize": "sexualise",
    "signalize": "signalise",
    "socialize": "socialise",
    "specialize": "specialise",
    "stabilize": "stabilise",
    "standardize": "standardise",
    "sterilize": "sterilise",
    "stigmatize": "stigmatise",
    "subsidize": "subsidise",
    "summarize": "summarise",
    "symbolize": "symbolise",
    "sympathize": "sympathise",
    "synchronize": "synchronise",
    "synthesize": "synthesise",
    "systematize": "systematise",
    "tantalize": "tantalise",
    "temporize": "temporise",
    "terrorize": "terrorise",
    "theorize": "theorise",
    "tranquilize": "tranquillise",
    "traumatize": "traumatise",
    "trivialize": "trivialise",
    "unionize": "unionise",
    "urbanize": "urbanise",
    "utilize": "utilise",
    "vandalize": "vandalise",
    "vaporize": "vaporise",
    "verbalize": "verbalise",
    "victimize": "victimise",
    "visualize": "visualise",
    "vocalize": "vocalise",
    "westernize": "westernise",

    // -yze → -yse
    "analyze": "analyse",
    "breathalyze": "breathalyse",
    "catalyze": "catalyse",
    "dialyze": "dialyse",
    "electrolyze": "electrolyse",
    "hydrolyze": "hydrolyse",
    "paralyze": "paralyse",
    "psychoanalyze": "psychoanalyse",

    // -or → -our
    "arbor": "arbour",
    "armor": "armour",
    "behavior": "behaviour",
    "candor": "candour",
    "clamor": "clamour",
    "color": "colour",
    "demeanor": "demeanour",
    "endeavor": "endeavour",
    "favor": "favour",
    "fervor": "fervour",
    "flavor": "flavour",
    "harbor": "harbour",
    "honor": "honour",
    "humor": "humour",
    "labor": "labour",
    "neighbor": "neighbour",
    "odor": "odour",
    "parlor": "parlour",
    "rancor": "rancour",
    "rigor": "rigour",
    "rumor": "rumour",
    "savior": "saviour",
    "savor": "savour",
    "splendor": "splendour",
    "succor": "succour",
    "tumor": "tumour",
    "valor": "valour",
    "vapor": "vapour",
    "vigor": "vigour",

    // -er → -re
    "caliber": "calibre",
    "center": "centre",
    "fiber": "fibre",
    "liter": "litre",
    "luster": "lustre",
    "maneuver": "manoeuvre",
    "meager": "meagre",
    "meter": "metre",
    "ocher": "ochre",
    "reconnoiter": "reconnoitre",
    "saber": "sabre",
    "scepter": "sceptre",
    "sepulcher": "sepulchre",
    "somber": "sombre",
    "specter": "spectre",
    "theater": "theatre",

    // -ense → -ence
    "defense": "defence",
    "license": "licence",
    "offense": "offence",
    "pretense": "pretence",

    // -og → -ogue
    "analog": "analogue",
    "catalog": "catalogue",
    "dialog": "dialogue",
    "epilog": "epilogue",
    "monolog": "monologue",
    "prolog": "prologue",

    // Single → double consonants
    "canceled": "cancelled",
    "canceling": "cancelling",
    "councilor": "councillor",
    "counseled": "counselled",
    "counseling": "counselling",
    "counselor": "counsellor",
    "crueler": "crueller",
    "cruelest": "cruellest",
    "dialed": "dialled",
    "dialing": "dialling",
    "dueled": "duelled",
    "dueling": "duelling",
    "fueled": "fuelled",
    "fueling": "fuelling",
    "initialed": "initialled",
    "initialing": "initialling",
    "jeweled": "jewelled",
    "jeweler": "jeweller",
    "labeled": "labelled",
    "labeling": "labelling",
    "leveled": "levelled",
    "leveling": "levelling",
    "marshaled": "marshalled",
    "marshaling": "marshalling",
    "marveled": "marvelled",
    "marveling": "marvelling",
    "marvelous": "marvellous",
    "modeled": "modelled",
    "modeling": "modelling",
    "paneled": "panelled",
    "paneling": "panelling",
    "parceled": "parcelled",
    "parceling": "parcelling",
    "penciled": "pencilled",
    "penciling": "pencilling",
    "quarreled": "quarrelled",
    "quarreling": "quarrelling",
    "raveled": "ravelled",
    "raveling": "ravelling",
    "rivaled": "rivalled",
    "rivaling": "rivalling",
    "shoveled": "shovelled",
    "shoveling": "shovelling",
    "signaled": "signalled",
    "signaling": "signalling",
    "spiraled": "spiralled",
    "spiraling": "spiralling",
    "stenciled": "stencilled",
    "stenciling": "stencilling",
    "traveled": "travelled",
    "traveler": "traveller",
    "traveling": "travelling",
    "tunneled": "tunnelled",
    "tunneling": "tunnelling",
    "unraveled": "unravelled",
    "unraveling": "unravelling",
    "worshiped": "worshipped",
    "worshiper": "worshipper",
    "worshiping": "worshipping",

    // Other common differences
    "acknowledgment": "acknowledgement",
    "aging": "ageing",
    "airplane": "aeroplane",
    "aluminum": "aluminium",
    "artifact": "artefact",
    "ax": "axe",
    "check": "cheque",
    "cozy": "cosy",
    "curb": "kerb",
    "donut": "doughnut",
    "draft": "draught",
    "draftsman": "draughtsman",
    "fulfill": "fulfil",
    "gray": "grey",
    "installment": "instalment",
    "jail": "gaol",
    "jewelry": "jewellery",
    "judgment": "judgement",
    "licorice": "liquorice",
    "mold": "mould",
    "molding": "moulding",
    "molt": "moult",
    "mom": "mum",
    "mustache": "moustache",
    "pajamas": "pyjamas",
    "peddler": "pedlar",
    "plow": "plough",
    "skeptic": "sceptic",
    "skeptical": "sceptical",
    "skepticism": "scepticism",
    "skillful": "skilful",
    "smolder": "smoulder",
    "sulfur": "sulphur",
    "tire": "tyre",
    "willful": "wilful",
    "woolen": "woollen"
};

// Generate all verb forms (-ed, -es, -ing) for -ize/-ise words
function generateVerbForms(baseSpellings) {
    const expanded = { ...baseSpellings };
    
    for (const [us, au] of Object.entries(baseSpellings)) {
        // Only process -ize → -ise conversions
        if (us.endsWith('ize') && au.endsWith('ise')) {
            const usBase = us.slice(0, -1); // remove 'e'
            const auBase = au.slice(0, -1);
            
            // -ized → -ised
            expanded[usBase + 'ed'] = auBase + 'ed';
            // -izes → -ises
            expanded[us + 's'] = au + 's';
            // -izing → -ising
            expanded[usBase + 'ing'] = auBase + 'ing';
            // -ization → -isation
            expanded[usBase.slice(0, -2) + 'ization'] = auBase.slice(0, -2) + 'isation';
            expanded[usBase.slice(0, -2) + 'izations'] = auBase.slice(0, -2) + 'isations';
        }
        
        // -yze → -yse conversions
        if (us.endsWith('yze') && au.endsWith('yse')) {
            const usBase = us.slice(0, -1);
            const auBase = au.slice(0, -1);
            
            expanded[usBase + 'ed'] = auBase + 'ed';
            expanded[us + 's'] = au + 's';
            expanded[usBase + 'ing'] = auBase + 'ing';
            expanded[us.slice(0, -3) + 'ysis'] = au.slice(0, -3) + 'ysis';
            expanded[us.slice(0, -3) + 'yses'] = au.slice(0, -3) + 'yses';
        }
    }
    
    return expanded;
}

// Export the complete dictionary with all verb forms
const SPELLINGS = generateVerbForms(US_TO_AU_SPELLINGS);

/**
 * Common errors and misspellings
 * These are always wrong - not US/AU differences
 * Based on Style Manual: https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/spelling/common-misspellings-and-word-confusion
 */
const COMMON_ERRORS = {
    // "Would of" etc. - mishearing of "would've"
    "could of": "could have",
    "should of": "should have",
    "would of": "would have",
    "must of": "must have",
    "might of": "might have",
    
    // Commonly confused phrases
    "deep-seeded": "deep-seated",
    "deep seeded": "deep-seated",
    "free reign": "free rein",
    "intensive purposes": "intents and purposes",
    "leadway": "leeway",
    "mute point": "moot point",
    "on tenderhooks": "on tenterhooks",
    "tenderhooks": "tenterhooks",
    "peak interest": "pique interest",
    "peaked interest": "piqued interest",
    "peaks interest": "piques interest",
    "peaking interest": "piquing interest",
    
    // Always wrong
    "irregardless": "regardless",
    
    // World Wars - use roman numerals
    "WW1": "WWI",
    "WW2": "WWII",
    "World War 1": "World War I",
    "World War 2": "World War II",
    
    // Style Manual preference
    "programme": "program",
    "programmes": "programs",
    "programmed": "programmed",
    "programming": "programming",
    
    // Master degree - no apostrophe
    "master's degree": "master degree",
    "masters degree": "master degree",
    "master's degrees": "master degrees",
    "masters degrees": "master degrees",
    
    // Australian past tense
    "dove into": "dived into",
    "dove in": "dived in",
    "dove down": "dived down"
};

/**
 * Errors that need special notes/caveats
 */
const ERRORS_WITH_NOTES = {
    "judgment": {
        suggestion: "judgement",
        note: "Use 'judgement' unless referring to a court judgment"
    }
};

/**
 * Watch words - words to reconsider for plain language
 * Based on Style Manual: https://www.stylemanual.gov.au/writing-and-designing-content/clear-language-and-writing-style/plain-language-and-word-choice
 */
const WATCH_WORDS = {
    "a number of": "Tell people how many there were, or consider using 'some', 'many' or 'few'.",
    "absolutely": "Do not use (unnecessary modifier).",
    "acquire": "Consider using 'buy' or 'get' instead.",
    "actress": "Consider using 'actor'.",
    "additional": "Consider using 'more' or 'extra'.",
    "address the issue": "Consider using 'solve the problem' or 'answer the question'.",
    "adequate number of": "Consider using 'enough'.",
    "advising in relation to": "Consider using 'advising on' or 'advising about'.",
    "agenda": "Do not use (unless related to a meeting).",
    "amongst": "Consider using 'among'.",
    "approximately": "Consider using 'about'.",
    "as a consequence of": "Consider using 'because'.",
    "ascertain": "Consider using 'find out'.",
    "assist": "Consider using 'help', 'support' or 'guide'.",
    "at a later date": "Specify a timeframe or consider using 'later' or 'soon'.",
    "at the end of the day": "Consider using 'realistically'.",
    "at the time of writing": "Consider using 'now'.",
    "at this point in time": "Consider using 'now'.",
    "attempt": "When used as a verb, use 'try'.",
    "basically": "Do not use (unnecessary modifier).",
    "cease": "Consider using 'stop' or 'end'.",
    "certainly": "Do not use (unnecessary modifier).",
    "clergyman": "Use 'minister of religion'.",
    "cognisant of": "Consider using 'know' or 'aware of'.",
    "collaborate with": "Consider using 'work with'.",
    "commence": "Consider using 'start' or 'begin'.",
    "comprehensive": "Consider using 'full', 'complete', 'broad' or 'all-round'.",
    "concerning": "Consider using 'about'.",
    "consensus of opinion": "Consider using 'agreement' or 'consensus'.",
    "consequence": "Consider using 'result'.",
    "consequently": "Consider using 'so'.",
    "considerable": "Consider using 'many' or 'long'.",
    "construct": "Consider using 'build' or 'make'.",
    "create a dialogue": "Consider using 'speak', 'discuss' or 'talk'.",
    "currently": "Consider using 'now', or delete. Only use if you want to distinguish actions in the current time from those in the past.",
    "deficiency": "Consider using 'lack of'.",
    "deliver": "Say what you are doing – for example, 'increasing'.",
    "drive": "Say what you are doing – for example, 'increasing'.",
    "demonstrate": "Consider using 'show'.",
    "desire": "Consider using 'want'.",
    "despite the fact that": "Consider using 'although' or breaking up the sentence to avoid this phrase.",
    "determine": "Consider using 'decide' or 'find out'.",
    "disburse": "Consider using 'pay'.",
    "discontinue": "Consider using 'stop' or 'end'.",
    "dispatch": "Consider using 'send'.",
    "documentation": "Consider using 'documents'.",
    "due to the fact that": "Consider using 'because'.",
    "during the month of": "Consider using 'in [month]'.",
    "endeavour": "Consider using 'try'.",
    "enhance": "Consider using 'improve'.",
    "enquire": "Consider using 'ask'.",
    "establish": "Consider using 'create', 'set up' or 'form'.",
    "examine": "Consider using 'look at', 'check' or 'discuss'.",
    "exit": "If using as a verb, use 'leave'.",
    "facilitate": "Consider using 'help', 'ease', 'simplify' or 'organise'.",
    "fireman": "Consider using 'firefighter'.",
    "for a period of": "Consider using 'for' or 'to'.",
    "for the purpose of": "Consider using 'for'.",
    "for the reason that": "Consider using 'because' or 'since'.",
    "foreman": "Consider using 'supervisor'.",
    "forthwith": "Consider using 'now' or 'at once'.",
    "fundamental": "Cut, or use 'main' or 'basic'.",
    "furthermore": "Cut, or use 'and'.",
    "give consideration to": "Consider using 'think about' or 'consider'.",
    "going forward": "Consider using 'in future'.",
    "have the capacity to": "Consider using 'can'.",
    "heretofore": "Consider using 'until now'.",
    "hopefully": "Do not use (unnecessary modifier).",
    "hostess": "Use 'host'.",
    "if this is not the case": "Consider using 'if not'.",
    "if this is the case": "Consider using 'if so'.",
    "impact": "If using as a verb, use 'affect'.",
    "impact on": "Consider using 'affect'.",
    "implement": "Consider using 'apply', 'install', 'do', 'start' or 'carry out'.",
    "important": "Consider using 'main'.",
    "in accordance with": "Consider using 'by', 'under' or 'according to'.",
    "in an effort to": "Consider using 'to'.",
    "in as much as": "Consider using 'because' or 'since'.",
    "in conjunction with": "Consider using 'with'.",
    "in connection with": "Consider using 'about'.",
    "in excess of": "Consider using 'over', 'higher than' or 'more than'.",
    "in lieu of": "Consider using 'instead of'.",
    "in light of": "Consider using 'if', 'because', 'since' or 'when'.",
    "in order to": "Consider using 'to'.",
    "in receipt of": "Consider using 'get', 'have', 'receive' or 'receiving'.",
    "in regards to": "Consider using 'about' or 'on'.",
    "in relation to": "Consider using 'about' or 'on'.",
    "in respect of": "Consider using 'about' or 'on'.",
    "in the absence of": "Consider using 'without'.",
    "in the case of": "Consider using 'if' or 'for'.",
    "in the event that": "Consider using 'if' or 'when'.",
    "in the final analysis": "Do not use.",
    "in the near future": "Consider using 'soon'.",
    "in this connection": "Consider using 'about'.",
    "in this day and age": "Consider using 'today'.",
    "in view of the fact that": "Consider using 'because'.",
    "inquire": "Consider using 'ask'.",
    "inter alia": "Cut, or use 'among other things'.",
    "is unable to": "Consider using 'can't' or 'cannot'.",
    "it is requested that you declare": "Consider using 'declare'.",
    "it should be noted that": "Consider using 'note that' or 'remember that'.",
    "join together": "Consider using 'join'.",
    "last but not least": "Cut, or use 'finally'.",
    "leverage": "Consider using 'use' or 'build on'.",
    "make a complaint": "Consider using 'complain'.",
    "make an application": "Consider using 'apply'.",
    "manner": "Consider using 'way'.",
    "methodology": "Consider using 'method' in most cases.",
    "necessitate": "Consider using 'need'.",
    "notwithstanding": "Consider using 'even though', 'though', 'even if' or 'despite'.",
    "numerous": "Consider using 'many'.",
    "objective": "Consider using 'aim', 'end' or 'purpose'.",
    "obtain": "Consider using 'get' or 'have'.",
    "obviously": "Do not use (unnecessary modifier).",
    "on a daily basis": "Consider using 'daily'.",
    "on behalf of": "Consider using 'for'.",
    "on the basis of": "Consider using 'because of', 'based on' or 'since'.",
    "optimum": "Consider using 'best'.",
    "past experience": "Consider using 'experience'.",
    "per annum": "Consider using 'per year'. English is more accessible than Latin.",
    "per capita": "Consider using 'per person'. English is more accessible than Latin.",
    "policeman": "Consider using 'police officer'.",
    "presently": "Consider using 'now'.",
    "preventative": "Consider using 'preventive'.",
    "primary": "Consider using 'main'.",
    "prior to": "Consider using 'before'.",
    "provide": "Consider using 'give'.",
    "provide a response to": "Consider using 'respond to'.",
    "provide assistance with": "Consider using 'help' or 'support'.",
    "pursuant to": "Consider using 'under'.",
    "reach a decision": "Consider using 'decide'.",
    "make a decision": "Consider using 'decide'.",
    "require": "Consider using 'need' or 'must'.",
    "retain": "Consider using 'keep'.",
    "stewardess": "Consider using 'flight attendant'.",
    "subsequently": "Consider using 'after'.",
    "substantiate": "Consider using 'prove'.",
    "table": "If a verb, use 'address', 'discuss' or 'release' (unless tabling a document in parliament).",
    "terminate": "Consider using 'end' (unless in a legal document).",
    "that is the reason why": "Consider using 'that is why'.",
    "the reason is because": "Consider using 'the reason is' or 'because'.",
    "the way in which": "Consider using 'how'.",
    "thereafter": "Consider using 'then' or 'afterwards'.",
    "until such time as": "Consider using 'until'.",
    "upon": "Consider using 'on'.",
    "utilise": "Consider using 'use'.",
    "virtually": "Consider using 'near' or 'almost'.",
    "waitress": "Use 'waiter'.",
    "whilst": "Use 'while'.",
    "with reference to": "Consider using 'about'.",
    "with regard to": "Consider using 'about'.",
    "with respect to": "Consider using 'about'."
};
