/**
 * US to Australian English spelling mappings
 * Based on Australian Government Style Manual guidance
 * https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/spelling
 */

const US_TO_AU_SPELLINGS = {
    // -ize → -ise (comprehensive list)
    "acclimatize": "acclimatise",
    "agonize": "agonise",
    "alphabetize": "alphabetise",
    "amortize": "amortise",
    "antagonize": "antagonise",
    "apologize": "apologise",
    "authorize": "authorise",
    "baptize": "baptise",
    "capitalize": "capitalise",
    "categorize": "categorise",
    "cauterize": "cauterise",
    "centralize": "centralise",
    "characterize": "characterise",
    "civilize": "civilise",
    "colonize": "colonise",
    "compartmentalize": "compartmentalise",
    "computerize": "computerise",
    "conceptualize": "conceptualise",
    "contextualize": "contextualise",
    "criticize": "criticise",
    "customize": "customise",
    "decentralize": "decentralise",
    "decolonize": "decolonise",
    "democratize": "democratise",
    "demobilize": "demobilise",
    "demonize": "demonise",
    "depoliticize": "depoliticise",
    "digitize": "digitise",
    "disincentivize": "disincentivise",
    "disorganize": "disorganise",
    "dramatize": "dramatise",
    "economize": "economise",
    "emphasize": "emphasise",
    "energize": "energise",
    "epitomize": "epitomise",
    "equalize": "equalise",
    "evangelize": "evangelise",
    "exorcize": "exorcise",
    "externalize": "externalise",
    "familiarize": "familiarise",
    "fantasize": "fantasise",
    "federalize": "federalise",
    "fertilize": "fertilise",
    "finalize": "finalise",
    "formalize": "formalise",
    "fossilize": "fossilise",
    "galvanize": "galvanise",
    "generalize": "generalise",
    "glamorize": "glamorise",
    "globalize": "globalise",
    "harmonize": "harmonise",
    "homogenize": "homogenise",
    "hospitalize": "hospitalise",
    "humanize": "humanise",
    "hybridize": "hybridise",
    "hypnotize": "hypnotise",
    "hypothesize": "hypothesise",
    "idealize": "idealise",
    "immobilize": "immobilise",
    "immunize": "immunise",
    "incentivize": "incentivise",
    "individualize": "individualise",
    "industrialize": "industrialise",
    "initialize": "initialise",
    "institutionalize": "institutionalise",
    "internalize": "internalise",
    "internationalize": "internationalise",
    "ionize": "ionise",
    "italicize": "italicise",
    "itemize": "itemise",
    "jeopardize": "jeopardise",
    "legalize": "legalise",
    "legitimize": "legitimise",
    "liberalize": "liberalise",
    "lionize": "lionise",
    "localize": "localise",
    "magnetize": "magnetise",
    "marginalize": "marginalise",
    "materialize": "materialise",
    "maximize": "maximise",
    "mechanize": "mechanise",
    "memorize": "memorise",
    "mesmerize": "mesmerise",
    "metabolize": "metabolise",
    "militarize": "militarise",
    "minimize": "minimise",
    "mobilize": "mobilise",
    "modernize": "modernise",
    "monetize": "monetise",
    "monopolize": "monopolise",
    "moralize": "moralise",
    "nationalize": "nationalise",
    "naturalize": "naturalise",
    "neutralize": "neutralise",
    "normalize": "normalise",
    "optimize": "optimise",
    "organize": "organise",
    "ostracize": "ostracise",
    "oxidize": "oxidise",
    "pasteurize": "pasteurise",
    "patronize": "patronise",
    "penalize": "penalise",
    "personalize": "personalise",
    "plagiarize": "plagiarise",
    "polarize": "polarise",
    "politicize": "politicise",
    "popularize": "popularise",
    "pressurize": "pressurise",
    "prioritize": "prioritise",
    "privatize": "privatise",
    "professionalize": "professionalise",
    "publicize": "publicise",
    "pulverize": "pulverise",
    "radicalize": "radicalise",
    "randomize": "randomise",
    "rationalize": "rationalise",
    "realize": "realise",
    "recognize": "recognise",
    "regularize": "regularise",
    "reorganize": "reorganise",
    "revitalize": "revitalise",
    "revolutionize": "revolutionise",
    "romanticize": "romanticise",
    "sanitize": "sanitise",
    "satirize": "satirise",
    "scandalize": "scandalise",
    "scrutinize": "scrutinise",
    "secularize": "secularise",
    "sensitize": "sensitise",
    "serialize": "serialise",
    "sexualize": "sexualise",
    "signalize": "signalise",
    "socialize": "socialise",
    "specialize": "specialise",
    "stabilize": "stabilise",
    "standardize": "standardise",
    "sterilize": "sterilise",
    "stigmatize": "stigmatise",
    "subsidize": "subsidise",
    "summarize": "summarise",
    "symbolize": "symbolise",
    "sympathize": "sympathise",
    "synchronize": "synchronise",
    "synthesize": "synthesise",
    "systematize": "systematise",
    "tantalize": "tantalise",
    "temporize": "temporise",
    "terrorize": "terrorise",
    "theorize": "theorise",
    "tranquilize": "tranquillise",
    "traumatize": "traumatise",
    "trivialize": "trivialise",
    "unionize": "unionise",
    "urbanize": "urbanise",
    "utilize": "utilise",
    "vandalize": "vandalise",
    "vaporize": "vaporise",
    "verbalize": "verbalise",
    "victimize": "victimise",
    "visualize": "visualise",
    "vocalize": "vocalise",
    "westernize": "westernise",

    // -yze → -yse
    "analyze": "analyse",
    "breathalyze": "breathalyse",
    "catalyze": "catalyse",
    "dialyze": "dialyse",
    "electrolyze": "electrolyse",
    "hydrolyze": "hydrolyse",
    "paralyze": "paralyse",
    "psychoanalyze": "psychoanalyse",

    // -or → -our
    "arbor": "arbour",
    "armor": "armour",
    "behavior": "behaviour",
    "candor": "candour",
    "clamor": "clamour",
    "color": "colour",
    "demeanor": "demeanour",
    "endeavor": "endeavour",
    "favor": "favour",
    "fervor": "fervour",
    "flavor": "flavour",
    "harbor": "harbour",
    "honor": "honour",
    "humor": "humour",
    "labor": "labour",
    "neighbor": "neighbour",
    "odor": "odour",
    "parlor": "parlour",
    "rancor": "rancour",
    "rigor": "rigour",
    "rumor": "rumour",
    "savior": "saviour",
    "savor": "savour",
    "splendor": "splendour",
    "succor": "succour",
    "tumor": "tumour",
    "valor": "valour",
    "vapor": "vapour",
    "vigor": "vigour",

    // -er → -re (derived forms are explicit because -re morphology is
    // irregular: centre + ed = centred. 'metered' is deliberately absent -
    // a measuring device is a 'meter' in Australian English too.)
    "caliber": "calibre",
    "calibers": "calibres",
    "center": "centre",
    "centers": "centres",
    "centered": "centred",
    "centering": "centring",
    "fiber": "fibre",
    "fibers": "fibres",
    "liter": "litre",
    "liters": "litres",
    "luster": "lustre",
    "maneuver": "manoeuvre",
    "maneuvers": "manoeuvres",
    "maneuvered": "manoeuvred",
    "maneuvering": "manoeuvring",
    "meager": "meagre",
    "meter": "metre",
    "meters": "metres",
    "ocher": "ochre",
    "reconnoiter": "reconnoitre",
    "reconnoitered": "reconnoitred",
    "reconnoitering": "reconnoitring",
    "saber": "sabre",
    "sabers": "sabres",
    "scepter": "sceptre",
    "scepters": "sceptres",
    "sepulcher": "sepulchre",
    "sepulchers": "sepulchres",
    "somber": "sombre",
    "specter": "spectre",
    "specters": "spectres",
    "theater": "theatre",
    "theaters": "theatres",

    // -ense → -ence ('licensed'/'licensing'/'licenses' are NOT flagged
    // anywhere: 'license' is the Australian verb spelling)
    "defense": "defence",
    "defenses": "defences",
    "license": "licence",
    "offense": "offence",
    "offenses": "offences",
    "pretense": "pretence",
    "pretenses": "pretences",

    // -og → -ogue
    "analog": "analogue",
    "catalog": "catalogue",
    "dialog": "dialogue",
    "epilog": "epilogue",
    "monolog": "monologue",
    "prolog": "prologue",

    // Single → double consonants
    "canceled": "cancelled",
    "canceling": "cancelling",
    "councilor": "councillor",
    "counseled": "counselled",
    "counseling": "counselling",
    "counselor": "counsellor",
    "crueler": "crueller",
    "cruelest": "cruellest",
    "dialed": "dialled",
    "dialing": "dialling",
    "dueled": "duelled",
    "dueling": "duelling",
    "fueled": "fuelled",
    "fueling": "fuelling",
    "initialed": "initialled",
    "initialing": "initialling",
    "jeweled": "jewelled",
    "jeweler": "jeweller",
    "labeled": "labelled",
    "labeling": "labelling",
    "leveled": "levelled",
    "leveling": "levelling",
    "marshaled": "marshalled",
    "marshaling": "marshalling",
    "marveled": "marvelled",
    "marveling": "marvelling",
    "marvelous": "marvellous",
    "modeled": "modelled",
    "modeling": "modelling",
    "paneled": "panelled",
    "paneling": "panelling",
    "parceled": "parcelled",
    "parceling": "parcelling",
    "penciled": "pencilled",
    "penciling": "pencilling",
    "quarreled": "quarrelled",
    "quarreling": "quarrelling",
    "raveled": "ravelled",
    "raveling": "ravelling",
    "rivaled": "rivalled",
    "rivaling": "rivalling",
    "shoveled": "shovelled",
    "shoveling": "shovelling",
    "signaled": "signalled",
    "signaling": "signalling",
    "spiraled": "spiralled",
    "spiraling": "spiralling",
    "stenciled": "stencilled",
    "stenciling": "stencilling",
    "traveled": "travelled",
    "traveler": "traveller",
    "traveling": "travelling",
    "tunneled": "tunnelled",
    "tunneling": "tunnelling",
    "unraveled": "unravelled",
    "unraveling": "unravelling",
    "worshiped": "worshipped",
    "worshiper": "worshipper",
    "worshiping": "worshipping",

    // Other common differences
    "acknowledgment": "acknowledgement",
    "aging": "ageing",
    "airplane": "aeroplane",
    "aluminum": "aluminium",
    "artifact": "artefact",
    "ax": "axe",
    "check": "cheque",
    "cozy": "cosy",
    "curb": "kerb",
    "donut": "doughnut",
    "draft": "draught",
    "draftsman": "draughtsman",
    "fulfill": "fulfil",
    "gray": "grey",
    "installment": "instalment",
    "jail": "gaol",
    "jewelry": "jewellery",
    "judgment": "judgement",
    "licorice": "liquorice",
    "mold": "mould",
    "molding": "moulding",
    "molt": "moult",
    "mom": "mum",
    "mustache": "moustache",
    "pajamas": "pyjamas",
    "peddler": "pedlar",
    "plow": "plough",
    "skeptic": "sceptic",
    "skeptical": "sceptical",
    "skepticism": "scepticism",
    "skillful": "skilful",
    "smolder": "smoulder",
    "sulfur": "sulphur",
    "tire": "tyre",
    "willful": "wilful",
    "woolen": "woollen"
};

// Generate all verb forms (-ed, -es, -ing) for -ize/-ise words
function generateVerbForms(baseSpellings) {
    const expanded = { ...baseSpellings };

    for (const [us, au] of Object.entries(baseSpellings)) {
        // Only process -ize → -ise conversions
        if (us.endsWith('ize') && au.endsWith('ise')) {
            const usBase = us.slice(0, -1); // remove 'e'
            const auBase = au.slice(0, -1);

            // -ized → -ised
            expanded[usBase + 'ed'] = auBase + 'ed';
            // -izes → -ises
            expanded[us + 's'] = au + 's';
            // -izing → -ising
            expanded[usBase + 'ing'] = auBase + 'ing';
            // -ization → -isation
            expanded[usBase.slice(0, -2) + 'ization'] = auBase.slice(0, -2) + 'isation';
            expanded[usBase.slice(0, -2) + 'izations'] = auBase.slice(0, -2) + 'isations';
        }

        // -yze → -yse conversions
        if (us.endsWith('yze') && au.endsWith('yse')) {
            const usBase = us.slice(0, -1);
            const auBase = au.slice(0, -1);

            expanded[usBase + 'ed'] = auBase + 'ed';
            expanded[us + 's'] = au + 's';
            expanded[usBase + 'ing'] = auBase + 'ing';
            expanded[us.slice(0, -3) + 'ysis'] = au.slice(0, -3) + 'ysis';
            expanded[us.slice(0, -3) + 'yses'] = au.slice(0, -3) + 'yses';
        }
    }

    return expanded;
}

// Export the complete dictionary with all verb forms
export const SPELLINGS = generateVerbForms(US_TO_AU_SPELLINGS);

/**
 * Common errors and misspellings
 * These are always wrong - not US/AU differences
 */
export const COMMON_ERRORS = {
    "could of": "could have",
    "should of": "should have",
    "would of": "would have",
    "must of": "must have",
    "might of": "might have",
    "deep-seeded": "deep-seated",
    "deep seeded": "deep-seated",
    "free reign": "free rein",
    "intensive purposes": "intents and purposes",
    "leadway": "leeway",
    "mute point": "moot point",
    "on tenderhooks": "on tenterhooks",
    "tenderhooks": "tenterhooks",
    "peak interest": "pique interest",
    "peaked interest": "piqued interest",
    "peaks interest": "piques interest",
    "peaking interest": "piquing interest",
    "irregardless": "regardless",
    "WW1": "WWI",
    "WW2": "WWII",
    "World War 1": "World War I",
    "World War 2": "World War II",
    "programme": "program",
    "programmes": "programs",
    "master's degree": "master degree",
    "masters degree": "master degree",
    "master's degrees": "master degrees",
    "masters degrees": "master degrees",
    "dove into": "dived into",
    "dove in": "dived in",
    "dove down": "dived down"
};

/**
 * Errors that need special notes/caveats
 */
export const ERRORS_WITH_NOTES = {
    "judgment": {
        suggestion: "judgement",
        note: "Use 'judgement' unless referring to a court judgment"
    }
};

/**
 * Watch words - words to reconsider for plain language
 */
export const WATCH_WORDS = {
    "acquire": "Consider using 'buy' or 'get' instead",
    "additional": "Consider using 'extra' or 'more'",
    "amongst": "Consider using 'among'",
    "approximately": "Consider using 'about'",
    "assist": "Consider using 'help', 'support' or 'guide'",
    "cease": "Consider using 'stop' or 'end'",
    "commence": "Consider using 'start' or 'begin'",
    "commencing": "Consider using 'starting'",
    "comprehensive": "Consider using 'full', 'complete', 'broad' or 'all-round'",
    "consequence": "Consider using 'result'",
    "consequently": "Consider using 'so'",
    "demonstrate": "Consider using 'show'",
    "determine": "Consider using 'decide' or 'find out'",
    "discontinue": "Consider using 'stop' or 'end'",
    "documentation": "Consider using 'documents'",
    "endeavour": "Consider using 'try'",
    "enhance": "Consider using 'improve'",
    "establish": "Consider using 'create', 'set up' or 'form'",
    "facilitate": "Consider using 'help', 'ease', 'simplify' or 'organise'",
    "forthwith": "Consider using 'now' or 'at once'",
    "furthermore": "Cut, or use 'and'",
    "implement": "Consider using 'apply', 'install', 'do', 'start' or 'carry out'",

    "leverage": "Consider using 'use' or 'build on'",
    "notwithstanding": "Consider using 'even though', 'though', 'even if' or 'despite'",
    "numerous": "Consider using 'many'",
    "obtain": "Consider using 'get' or 'have'",
    "optimum": "Consider using 'best'",
    "provide": "Consider using 'give'",
    "require": "Consider using 'need' or 'must'",
    "retain": "Consider using 'keep'",
    "subsequently": "Consider using 'after'",
    "terminate": "Consider using 'end' (unless in a legal document)",
    "utilise": "Consider using 'use'",
    "whilst": "Use 'while'"
};

// Gendered terms → inclusive alternatives
// Style Manual: https://www.stylemanual.gov.au/accessible-and-inclusive-content/inclusive-language/gender-and-sexual-diversity
export const GENDERED_TERMS = {
    "chairman": "Consider using 'chair' or 'chairperson'",
    "chairwoman": "Consider using 'chair' or 'chairperson'",
    "policeman": "Consider using 'police officer'",
    "policewoman": "Consider using 'police officer'",
    "fireman": "Consider using 'firefighter'",
    "firewoman": "Consider using 'firefighter'",
    "spokesman": "Consider using 'spokesperson'",
    "spokeswoman": "Consider using 'spokesperson'",
    "businessman": "Consider using 'businessperson' or 'executive'",
    "businesswoman": "Consider using 'businessperson' or 'executive'",
    "craftsman": "Consider using 'craftsperson' or 'artisan'",
    "salesman": "Consider using 'salesperson' or 'sales representative'",
    "saleswoman": "Consider using 'salesperson' or 'sales representative'",
    "workman": "Consider using 'worker'",
    "manpower": "Consider using 'workforce' or 'staffing'",
    "manning": "Consider using 'staffing' or 'operating'",
    "mankind": "Consider using 'humankind' or 'humanity'",
    "man-made": "Consider using 'synthetic', 'artificial' or 'manufactured'",
    "actress": "Consider using 'actor'",
    "hostess": "Consider using 'host'",
    "waitress": "Consider using 'waiter' or 'server'",
    "stewardess": "Consider using 'flight attendant'",
    "foreman": "Consider using 'supervisor' or 'foreperson'"
};

// Disability and neurodiversity terms → person-first language
// Style Manual: https://www.stylemanual.gov.au/accessible-and-inclusive-content/inclusive-language/disability-and-neurodiversity
export const DISABILITY_TERMS = {
    "handicapped": "Use person-first language: 'person with disability' or 'accessible' (for places)",
    "wheelchair-bound": "Consider using 'wheelchair user' or 'person who uses a wheelchair'",
    "wheelchair bound": "Consider using 'wheelchair user' or 'person who uses a wheelchair'",
    "suffers from": "Consider using 'has' or 'lives with' (avoid language that implies suffering)",
    "afflicted with": "Consider using 'has' or 'lives with'",
    "crippled": "Consider using 'person with disability'",
    "deaf and dumb": "Consider using 'Deaf', 'hard of hearing' or 'person who is Deaf'",
    "deaf-mute": "Consider using 'Deaf', 'hard of hearing' or 'person who is Deaf'",
    "hearing impaired": "Consider using 'hard of hearing' or 'Deaf'",
    "the disabled": "Consider using 'people with disability'",
    "the blind": "Consider using 'people who are blind' or 'people with vision impairment'",
    "able-bodied": "Consider using 'non-disabled' or 'people without disability'",
    "mentally ill": "Consider using 'person with mental health condition'",
    "mentally disabled": "Consider using 'person with intellectual disability' or 'person with cognitive disability'",
    "special needs": "Consider using 'disability support needs' or 'access needs'"
};

// Age diversity terms
// Style Manual: https://www.stylemanual.gov.au/accessible-and-inclusive-content/inclusive-language/age-diversity
export const AGE_TERMS = {
    "the elderly": "Consider using 'older people' or 'older Australians'",
    "elderly": "Consider using 'older people' or 'older Australians'",
    "the aged": "Consider using 'older people' or 'older Australians'",
    "senior citizens": "Consider using 'older people' or 'older Australians'",
    "old people": "Consider using 'older people' or 'older Australians'"
};

// Additional wordy phrases (supplements WATCH_WORDS)
// Style Manual: https://www.stylemanual.gov.au/writing-and-designing-content/clear-language-and-writing-style/plain-language-and-word-choice
export const WORDY_PHRASES = {
    "a number of": "Tell people how many there were, or consider using 'some', 'many' or 'few'",
    "adequate number of": "Consider using 'enough'",
    "at this point in time": "Consider using 'now'",
    "by means of": "Consider using 'by' or 'with'",
    "cognisant of": "Consider using 'know' or 'aware of'",
    "despite the fact that": "Consider using 'although' or 'even though'",
    "due to the fact that": "Consider using 'because'",
    "during the course of": "Consider using 'during'",
    "for the purpose of": "Consider using 'for'",
    "for the reason that": "Consider using 'because'",
    "give consideration to": "Consider using 'consider'",
    "going forward": "Consider using 'in future'",
    "in a position to": "Consider using 'can' or 'able to'",
    "in accordance with": "Consider using 'by', 'under' or 'according to'",
    "in order to": "Consider using 'to'",
    "in receipt of": "Consider using 'receive' or 'getting'",
    "in regards to": "Consider using 'about' or 'on'",
    "in relation to": "Consider using 'about' or 'on'",
    "in respect of": "Consider using 'about' or 'on'",
    "in the event that": "Consider using 'if' or 'when'",
    "in the near future": "Consider using 'soon'",
    "is able to": "Consider using 'can'",
    "it is important to note that": "Consider removing — go straight to the point",
    "on a regular basis": "Consider using 'regularly'",
    "on the grounds that": "Consider using 'because'",
    "pertaining to": "Consider using 'about' or 'on'",
    "prior to": "Consider using 'before'",
    "pursuant to": "Consider using 'under'",
    "whether or not": "Consider using 'whether'",
    "with reference to": "Consider using 'about'",
    "with regard to": "Consider using 'about'",
    "with respect to": "Consider using 'about'"
};

// PU-17: doubled-vowel prefix spellings (triage register, Batch 2).
// Two directions, both per the Macquarie Dictionary (checked July 2026):
// - closed-up doubled-vowel forms take a hyphen (reenter -> re-enter)
// - the co- family closes up (co-ordinate -> coordinate)
export const PREFIX_SPELLINGS = {
    // Add a hyphen (single-syllable prefix ending in the vowel that starts the word)
    "reenter": "re-enter", "reenters": "re-enters", "reentered": "re-entered",
    "reentering": "re-entering", "reentry": "re-entry", "reentries": "re-entries",
    "reexamine": "re-examine", "reexamines": "re-examines", "reexamined": "re-examined",
    "reexamining": "re-examining", "reexamination": "re-examination", "reexaminations": "re-examinations",
    "reelect": "re-elect", "reelects": "re-elects", "reelected": "re-elected",
    "reelecting": "re-electing", "reelection": "re-election", "reelections": "re-elections",
    "reemerge": "re-emerge", "reemerges": "re-emerges", "reemerged": "re-emerged",
    "reemerging": "re-emerging", "reemergence": "re-emergence",
    "reenact": "re-enact", "reenacts": "re-enacts", "reenacted": "re-enacted",
    "reenacting": "re-enacting", "reenactment": "re-enactment", "reenactments": "re-enactments",
    "reenrol": "re-enrol", "reenrols": "re-enrols", "reenrolled": "re-enrolled",
    "reenrolling": "re-enrolling", "reenrolment": "re-enrolment", "reenrolments": "re-enrolments",
    "reestablish": "re-establish", "reestablishes": "re-establishes", "reestablished": "re-established",
    "reestablishing": "re-establishing", "reestablishment": "re-establishment",
    "reevaluate": "re-evaluate", "reevaluates": "re-evaluates", "reevaluated": "re-evaluated",
    "reevaluating": "re-evaluating", "reevaluation": "re-evaluation", "reevaluations": "re-evaluations",
    "reengage": "re-engage", "reengages": "re-engages", "reengaged": "re-engaged",
    "reengaging": "re-engaging", "reengagement": "re-engagement",
    "reeducate": "re-educate", "reeducates": "re-educates", "reeducated": "re-educated",
    "reeducating": "re-educating", "reeducation": "re-education",
    "reemploy": "re-employ", "reemploys": "re-employs", "reemployed": "re-employed",
    "reemploying": "re-employing", "reemployment": "re-employment",
    "reenergise": "re-energise", "reenergises": "re-energises", "reenergised": "re-energised",
    "reenergising": "re-energising",
    "deemphasise": "de-emphasise", "deemphasises": "de-emphasises", "deemphasised": "de-emphasised",
    "deemphasising": "de-emphasising",
    "deescalate": "de-escalate", "deescalates": "de-escalates", "deescalated": "de-escalated",
    "deescalating": "de-escalating", "deescalation": "de-escalation",
    "deenergise": "de-energise", "deenergises": "de-energises", "deenergised": "de-energised",
    "deenergising": "de-energising",
    "preeminent": "pre-eminent", "preeminently": "pre-eminently", "preeminence": "pre-eminence",
    "preexist": "pre-exist", "preexists": "pre-exists", "preexisted": "pre-existed",
    "preexisting": "pre-existing",
    "preeclampsia": "pre-eclampsia",
    "preelection": "pre-election",
    "preempt": "pre-empt", "preempts": "pre-empts", "preempted": "pre-empted",
    "preempting": "pre-empting", "preemptive": "pre-emptive", "preemptively": "pre-emptively",
    "preemption": "pre-emption",
    "antiinflammatory": "anti-inflammatory", "antiinflammatories": "anti-inflammatories",
    "intraabdominal": "intra-abdominal", "intraarterial": "intra-arterial",
    "intraarticular": "intra-articular",

    // Remove the hyphen (Macquarie closes these up)
    "co-ordinate": "coordinate", "co-ordinates": "coordinates", "co-ordinated": "coordinated",
    "co-ordinating": "coordinating", "co-ordination": "coordination",
    "co-ordinator": "coordinator", "co-ordinators": "coordinators",
    "co-operate": "cooperate", "co-operates": "cooperates", "co-operated": "cooperated",
    "co-operating": "cooperating", "co-operation": "cooperation",
    "co-operative": "cooperative", "co-operatives": "cooperatives", "co-operatively": "cooperatively",
    "unco-operative": "uncooperative",
    "co-exist": "coexist", "co-exists": "coexists", "co-existed": "coexisted",
    "co-existing": "coexisting", "co-existence": "coexistence",
    "co-education": "coeducation", "co-educational": "coeducational",
    "co-opt": "coopt", "co-opts": "coopts", "co-opted": "coopted",
    "co-opting": "coopting", "co-option": "cooption",
    "micro-organism": "microorganism", "micro-organisms": "microorganisms"
};
